### ISSUE TITLE
ARM Docker build failures

### ISSUE THREAD

**Issue by sebdeckers** [commonshost/dohnut#11] opened 2019-04-28 02:58 UTC
@klutchell Any idea why the Docker builds for ARM are failing on Travis CI?

https://travis-ci.com/commonshost/dohnut/builds/109864713

**Comment by sebdeckers** [comment] 2019-04-28 03:04
Possibly related to:
- Node.js 12 release a few days ago
- https://github.com/sorccu/node-socket-activation/pull/1
- https://github.com/nodejs/docker-node/issues/873
- ...?

**Comment by klutchell** [comment] 2019-04-28 13:33
It seems that `npm install` running via qemu (for arm platforms) did not like the github url added in 1a20daccba230fff67da932141fc1a72b907574a.

I tried a few different syntax in `package.json` but could not get it to work.
I think there's an issue with qemu and github npm dependencies, which is why the amd64 builds still work. Even `npm install --verbose https://github.com/sebdeckers/node-socket-activation.git` just hangs.

In this case it's not related to Node.js 12 since we are using 11 in the docker image. I also tried using 12 as a test but it didn't help.

It also doesn't appear related to nodejs/docker-node#873 since we switch to the `node` user before running `npm install` to work around that very issue.

Fortunately https://github.com/sorccu/node-socket-activation/pull/1 has been merged now so we can just pick up `^3.2.0` going forward.

I'll continue to investigate the root cause since you should be able to use github urls as npm dependencies, but as we've both found there are a number of npm+qemu issues online.

**Comment by klutchell** [comment] 2019-04-28 14:41
Update: https://github.com/commonshost/dohnut/pull/12

Switching from npm to yarn resolved a number of installation issues, such as installing as root, and hanging during github dependencies. I tested installation with the old and the new `package.json` and it works with github urls now.

**Closed as completed** 2019-04-29 11:27 UTC

**Comment by sebdeckers** [comment] 2019-04-29 11:37
Thank you! Wow, what an obscure bug in NPM on ARM. Great find, and great solution.

FYI the Docker Hub image is proving very popular at [~1-2k pulls daily](https://hub.docker.com/v2/repositories/commonshost/dohnut/). 🤩

I am very excited about shipping the new Docker images with Node.js v12. Support for TLS session resumption and 1RTT or 0RTT handshakes should significantly reduce the CPU and network overhead of PING measurements to the DoH servers. Last week I noticed the popularity of Dohnut and its PING feature was causing such load on one of the servers that it looked like a DDoS.

**Comment by klutchell** [comment] 2019-04-29 12:07
Ah, I was wondering if you wanted to change the base docker image from Node 11 to Node 12.
I'll submit that change now.

**Comment by klutchell** [comment] 2019-04-29 12:13
Congrats on the popularity by the way! It's a great utility and I'm glad it's getting the attention it deserves.

Happy to be of help!
